import React from "react";
import Head from "next/head";
import styles from "../styles/pages.module.css";
import FillprojectData from "../components/FillprojectData";

function Filldata() {
  /* if (typeof window !== "undefined") {
    console.log(typeof window);
    history.pushState(null, null, location.href);
    window.onpopstate = function () {
      history.go(1);
    };
  } */

  return (
    <div className={styles.mainContainer}>
      <Head>
        <title>Fill Data</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FillprojectData />
    </div>
  );
}

export default Filldata;
