import Head from "next/head";
import React from "react";
import FillDataSubtypes from "../components/FillDataSubtypes";

const fillDataCommercial = () => {
  /* if (typeof window !== "undefined") {
    console.log(typeof window);
    history.pushState(null, null, location.href);
    window.onpopstate = function () {
      history.go(1);
    };
  } */

  return (
    <div>
      <Head>
        <title>Fill data | Commercial </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FillDataSubtypes />
    </div>
  );
};

export default fillDataCommercial;
