import Head from "next/head";
import React from "react";
import Subtype from "../components/Subtype";

const commercial = () => {
  /* if (typeof window !== "undefined") {
    console.log(typeof window);
    history.pushState(null, null, location.href);
    window.onpopstate = function () {
      history.go(1);
    };
  } */

  return (
    <div>
      <Head>
        <title>Choose Subtype | Agriha</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Subtype />
    </div>
  );
};

export default commercial;
